### ISSUE TITLE
TODO: Fix the baseUrl and NODE_PATH so this can have absolute paths from Source instead of relative paths (For better templates)

### ISSUE THREAD

**Issue by rnp-nsg** [mfdlabs/robloxlabs.com#96]

**Comment by rnp-nsg** [comment]
In the package.json, before execution of Start-Job, either run a task that sets it before node runs `NODE_PATH=./Source` Or set it in the .env

**Comment by rbx-nsg** [comment]
NODE_PATH is for modules, not solution files
