### ISSUE TITLE
About Nomad/config files

### ISSUE THREAD

**Issue by acb-it** [mfdlabs/robloxlabs.com#99]
Please remove the Nomad/Configs files on your public repositories, as your'e publishing private credentials from services you don't own or are allowed to use. Tinkering with private services usually is not a good thing to do, but at least don't make public information that can compromise these services.

Regards,

**Comment by rbx-nsg** [comment]
Sorry, I never realised I didn't .gitignore it

**Comment by rbx-nsg** [comment]
https://github.com/mfdlabs/robloxlabs.com/commit/2ed5cbc3db9ed7459fa7f2597100f4f8ca6b53a8

It is the best I can do
